### ISSUE TITLE
Strange result on location growth

### ISSUE THREAD

**Issue by stezarpriansya** [kvnoct/fast-api#1]
Hi Kevin, congrats for you good API!

Overall, your API is good, but i've found some strange result on the Location Growth endpoint. Why the number on location is same? Can you explain more on this?

And also try to write README file on your repo ya!

Thanks.

**Comment by kvnoct** [comment]
Hi Kak Stezar, 

Thank you for pointing out the error. I have fixed the bug and add the readme file.

**Comment by stezarpriansya** [comment]
Nice bro! keep learning!
